config/routes.rb
Rails.application.routes.draw do

  get 'users/novo'

  root  'static_pages#home'
  get   '/ajuda',    to: 'static_pages#ajuda'
  get   '/regra',    to: 'static_pages#regra'
  get   '/contato',  to: 'static_pages#contato'
  get   '/cadastro', to: 'users#novo'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase }
  validates :nome, presence:  true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def ola
  	render html: "Olá mundo Rails!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def ajuda
  end

  def regra

  end

  def contato

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def novo
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #Retorna o título completo por página
  def full_title(page_title = '')
    base_title = "BetsBolão sites de apostas do brasileirão"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Bets bolão do brasileirão &copy; 2017 todos os direitos reservados
  </small>
  <nav>
    <ul>
      <li><%= link_to "Regras", regra_path %></li>
      <li><%= link_to "Contatos", contato_path %></li>
      <li><a href="http://globoesporte.globo.com/" target="_blank">Nóticias</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Bets", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Ajuda", ajuda_path %></li>
        <li><%= link_to "Login", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= render 'layouts/shim' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= image_tag("img01.jpg", alt: "Bolão do brasileirão", class: "img-responsive") %>
  <%= render 'layouts/header' %>
  <div class="container-fluid">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/static_pages/ajuda.html.erb
<% provide(:title, "Ajuda") %>
<h1>Ajuda</h1>
	<p>Página onde os usuários irão tirar suas dúvidas</p>

app/views/static_pages/contato.html.erb
<%= provide(:title, "Contatos") %>
<h2>Está será a página de contatos</h2>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	<h1>Home</h1>
		<h2>
			Bem vindos. Ao nosso site de bolões e loterias
		</h2>
		<%= link_to 'Participe agora', cadastro_path, class: "btn btn-primary" %>
</div>

app/views/static_pages/regra.html.erb
<% provide(:title, "Regras") %>
<h1>Regras</h1>
	<p>Página onde terá u breve resumo da nossa empresa</p>

app/views/static_pages/sobre.html.erb
<% provide(:title, "Sobre") %>
<h1>Sobre</h1>
	<p>Página onde terá u breve resumo da nossa empresa</p>

app/views/users/novo.html.erb
<% provide(:title, "Cadastrar")
<h1>Cria conta</h1>
<p>Página onde novos usários farão seu cadastro</p>